export const data = JSON.parse("{\"key\":\"v-03f5d0d4\",\"path\":\"/EhLibDoc/20-components-for-planning-management/01-components-for-planning-and-event-management.html\",\"title\":\"Components for planning and visual interactive event management\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"The library contains a set of components for planning and visual interactive control events tied to a specific period of time. Component TPlannerDataSourceEh TPlannerDataSourceE...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/online-help-vuepress-hope/EhLibDoc/20-components-for-planning-management/01-components-for-planning-and-event-management.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"EhLib.VCL Developer’s guide\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Components for planning and visual interactive event management\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"The library contains a set of components for planning and visual interactive control events tied to a specific period of time. Component TPlannerDataSourceEh TPlannerDataSourceE...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":3,\"title\":\"Using the context menu in the components PlannerView\",\"slug\":\"using-the-context-menu-in-the-components-plannerview\",\"link\":\"#using-the-context-menu-in-the-components-plannerview\",\"children\":[]},{\"level\":3,\"title\":\"List of PlannerView events:\",\"slug\":\"list-of-plannerview-events\",\"link\":\"#list-of-plannerview-events\",\"children\":[]},{\"level\":3,\"title\":\"Component TPlannerCalendarPickerEh\",\"slug\":\"component-tplannercalendarpickereh\",\"link\":\"#component-tplannercalendarpickereh\",\"children\":[]},{\"level\":3,\"title\":\"Loading elements-events from DB or another storage.\",\"slug\":\"loading-elements-events-from-db-or-another-storage\",\"link\":\"#loading-elements-events-from-db-or-another-storage\",\"children\":[]},{\"level\":3,\"title\":\"Uploading of changed elements to DataBase.\",\"slug\":\"uploading-of-changed-elements-to-database\",\"link\":\"#uploading-of-changed-elements-to-database\",\"children\":[]},{\"level\":3,\"title\":\"Resources and events.\",\"slug\":\"resources-and-events\",\"link\":\"#resources-and-events\",\"children\":[]}],\"readingTime\":{\"minutes\":4.78,\"words\":1434},\"filePathRelative\":\"EhLibDoc/20-components-for-planning-management/01-components-for-planning-and-event-management.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
