<template><div><h1 id="working-with-tdbgrideh-at-design-time" tabindex="-1"><a class="header-anchor" href="#working-with-tdbgrideh-at-design-time" aria-hidden="true">#</a> Working with TDBGridEh at design-time</h1>
<p><img src="@source/images/DBGridEhDesignTime-01.png" alt="" loading="lazy"></p>
<p><code v-pre>TDBGridEh</code> contains rows and columns. Every row is a record in <code v-pre>TDataSet</code>. Every column is a field in <code v-pre>TDataSet</code>. Columns can be dynamic or static. Dynamic columns are recreated every time when the state of DataSet is changed. <code v-pre>State</code> of <code v-pre>DataSet</code> can be changed in several cases. It is changed when, for example, <code v-pre>DataSet</code> is reopened. When column is recreated, values of column properties are reset to their default values. It is useful to use dynamic columns when the list of fields of <code v-pre>DataSet</code> is not known in advance. In the mode of static columns grid itself never recreates columns. At design-time to create static columns you need to double-click on the grid. The <code v-pre>Columns Editor</code> window will be open. Press <code v-pre>Add all fields</code> in this window. Grid will create static column for every <code v-pre>DataSet</code> field.
<br/>
<br/></p>
<p><img src="@source/images/DBGridEhDesignTime-02.png" alt="" loading="lazy"></p>
<p>To customize properties of column you need to select its name in the The <code v-pre>Columns Editor</code> window. You can also select column in <code v-pre>Object Inspector</code> by clicking column title in the grid. If grid is connected to <code v-pre>DataSource</code> and <code v-pre>DataSource</code> is placed on the same Form as grid, then icon of <code v-pre>DataSource</code> will be shown in the bottom right corner of the Grid. You can click on the <code v-pre>DataSource</code> icon to select <code v-pre>DataSource</code> in <code v-pre>Object Inspector</code>. In same manner grid can show <code v-pre>DataSet</code>. If a <code v-pre>DataSet</code> is a <code v-pre>TMemTableEh</code> then grid also can show <code v-pre>TDataDriver</code> and <code v-pre>DataSet</code> which is connected to <code v-pre>DataDriver</code> as a <code v-pre>ProviderDataSet</code>.</p>
</div></template>


