<template><div><h1 id="fonts-and-coloring-of-the-data-grid" tabindex="-1"><a class="header-anchor" href="#fonts-and-coloring-of-the-data-grid" aria-hidden="true">#</a> Fonts and coloring of the data grid</h1>
<h3 id="working-with-the-grid-fonts" tabindex="-1"><a class="header-anchor" href="#working-with-the-grid-fonts" aria-hidden="true">#</a> Working with the Grid Fonts</h3>
<p>Use <code v-pre>TDBGridEh.Font</code> property to set the font for the entire grid. Changing the properties of <code v-pre>TDBGridEh</code>.Font will affect all cells of the grid that use the font &quot;Default&quot; or &quot;Not stored&quot;. For example, if you change the font in the column grid - <code v-pre>TColumnEh.Font</code>, font properties are locked at the column level, and it will always use the font <code v-pre>TColumnEh.Font</code> no matter how the <code v-pre>TDBGridEh.Font</code>. To return the column to the state when they are using the font <code v-pre>TDBGridEh.Font</code> it must be removed from the property value <code v-pre>cvFont</code> <code v-pre>TColumnEh.AssignedValues</code>. Each element of the grid, which have the Font property, has the additional property to set the state &quot;use the default font&quot; This property has a name a <code v-pre>AssignedValues</code> or <code v-pre>ParentFont</code>. For example, to work with the font header columns use properties <code v-pre>TitleParams.Font</code> of <code v-pre>TFont</code> type and <code v-pre>TitleParams.ParentFont</code> of <code v-pre>Boolean</code> type.</p>
<h3 id="the-background-color-of-the-cells-in-the-grid" tabindex="-1"><a class="header-anchor" href="#the-background-color-of-the-cells-in-the-grid" aria-hidden="true">#</a> The background color of the cells in the grid</h3>
<p>To set the background grid use the <code v-pre>TDBGridEh.Color</code> and <code v-pre>TDBGridEh.FixedColor</code> properties.
<code v-pre>TDBGridEh.Color</code> property is responsible for the background color in the cells of data and the areas not shaded cells. <code v-pre>TDBGridEh.FixedColor</code> property is responsible for the color of the fixed cells. Changing of the <code v-pre>TDBGridEh.Color</code> property will affect the entire grid cell that uses the background color of the &quot;default&quot; or &quot;Not stored&quot; state. For example, if you change the color in the column grid <code v-pre>TColumnEh.Color</code>, the color will be fixed at the column level, and it will always use the <code v-pre>TColumnEh.Color</code> regardless of how the property <code v-pre>TDBGridEh.Color</code> is changed. To return the column to the state when they use color <code v-pre>TDBGridEh.Color</code> the <code v-pre>cvColor</code> value must be removed <code v-pre>TColumnEh.AssignedValues</code> property. Each element of the grid which have a of <code v-pre>Color</code> property, also has the additional property to set the &quot;use color by default.&quot; This property has a <code v-pre>AssignedValues</code> or <code v-pre>ParentColor</code> name.</p>
<h3 id="font-and-background-data-cells" tabindex="-1"><a class="header-anchor" href="#font-and-background-data-cells" aria-hidden="true">#</a> Font and background data cells</h3>
<p>To customize the font and background colors of cells with data using the following properties:
<code v-pre>Columns[i].Font</code>, <code v-pre>Columns[i].Color</code> – to set the font and background colors for a particular column
<code v-pre>EvenRowColor</code>, <code v-pre>OddRowColor</code> – to set the color even and odd entries in the grid. To work correctly, the <code v-pre>DataSet</code> must correctly return the record number through the property <code v-pre>DataSet.RecNo</code>.</p>
<h3 id="_3d-и-flat-grid-style" tabindex="-1"><a class="header-anchor" href="#_3d-и-flat-grid-style" aria-hidden="true">#</a> 3D и flat grid style.</h3>
<p>Use the property <code v-pre>TDBGridEh.OptionsEh</code> to display / hide the frame around the 3D-fixed, fixed, footers and rows of data.
Use <code v-pre>TDBGridEh.Flat</code> property to display the grid in the &quot;flat-style&quot;.</p>
<h3 id="style-display-of-the-selected-cell-and-the-selection" tabindex="-1"><a class="header-anchor" href="#style-display-of-the-selected-cell-and-the-selection" aria-hidden="true">#</a> Style display of the selected cell and the selection</h3>
<p>By default, the grid automatically adjusts the style of shading selected cell and fixed-grid areas, depending on the color scheme Windows and project settings in IDE Project <code v-pre>Options-&gt; Application-&gt; Runtime thems</code>.</p>
<p>In Classic mode, the cell is painted with a solid color</p>
<p><img src="@source/images/clip0011.png" alt="" loading="lazy"></p>
<p>Themed mode uses a grid class objects <code v-pre>Vcl.Themes.StyleServices</code> to fill cells in a certain style.</p>
<p><img src="@source/images/clip0012.png" alt="" loading="lazy"></p>
<p>You can set the style of the selected cell staining for each individual using the <code v-pre>SelectionDrawParams</code>.<code v-pre>SelectionStyle</code> and <code v-pre>SelectionDrawParams.DrawFocusFrame</code> property.
You can also set the style of the selected cell globally for all project Grids. To do this, use the properties of the global object and <code v-pre>GridsEh.GridDefaultDrawStyleEh.SelectionStyle</code> GridsEh.<code v-pre>GridDefaultDrawStyleEh.DrawFocusFrame</code>.</p>
<h3 id="selecting-and-highlighting-the-current-record" tabindex="-1"><a class="header-anchor" href="#selecting-and-highlighting-the-current-record" aria-hidden="true">#</a> Selecting and highlighting the current record</h3>
<p>To activate, when the grid is always select the whole record, set <code v-pre>dgRowSelect</code> value in the <code v-pre>Options</code> property.
To illuminate the current record in the grid, set <code v-pre>dghRowHighlight</code> value in the <code v-pre>OptionsEh</code> property.</p>
</div></template>


