<template><div><h1 id="working-with-autoincrement-fields" tabindex="-1"><a class="header-anchor" href="#working-with-autoincrement-fields" aria-hidden="true">#</a> Working with AutoIncrement fields</h1>
<p><code v-pre>TMemTableEh</code> has an <code v-pre>AutoIncrement</code> property with <code v-pre>InitValue</code> and <code v-pre>Step</code> subproperties to work with fields which values are generated by automatic sequence numbers.</p>
<p>For such fields property <code v-pre>TField.AutoGenerateValue</code> must be <code v-pre>arAutoInc</code>. Values for such fields are generated automatically using internal counter when the new record is appeared in the internal array. Initial value of the counter is assigned by the <code v-pre>TMemTableEh.InitValue</code> property.</p>
<p>After inserting new record, a value of the counter increases on the number given by the <code v-pre>TMemTableEh.Step</code> property.</p>
<p>If <code v-pre>TMemTableEh</code> is connected to <code v-pre>DataDriver</code> then usually values of such fields are generated by the server. To cause <code v-pre>TMemTableEh</code> be able to get values of fields generated by the server, it is recommended to use <code v-pre>TMemTableEh</code> and <code v-pre>TSQLDataDriver</code> (or inherited from it) as follow:
Set <code v-pre>InitValue</code> property and <code v-pre>Step</code> property to -1. <code v-pre>Values</code> of <code v-pre>AutoIncrement</code> fields will have negative values before sending the new record to the server.</p>
<p>Add parameters in <code v-pre>TSQLDataDriver.SpecParams</code> property to make <code v-pre>SQLDataDriver</code> be able to get values of <code v-pre>AutoIncrement</code> fields generated by the server.</p>
<p>List of parameters in <code v-pre>TSQLDataDriver.SpecParams</code> depends on the type of <code v-pre>Server</code> and will be described later. After updates are applied and record new writes to the server, <code v-pre>SQLDataDriver</code> will request new value of the counter from server and assign it to the <code v-pre>AutoIncrement</code> field on the client.</p>
</div></template>


