<template><div><h1 id="tsqldatadrivereh-or-txxxdatadrivereh-which-one-is-best-to-use" tabindex="-1"><a class="header-anchor" href="#tsqldatadrivereh-or-txxxdatadrivereh-which-one-is-best-to-use" aria-hidden="true">#</a> TSQLDataDriverEh or TXXXDataDriverEh, which one is best to use</h1>
<p>As <code v-pre>TSQLDataDriverEh</code> as one of the <code v-pre>TBDEDataDriverEh</code>, <code v-pre>TIBXDataDriverEh</code>, <code v-pre>TDBXDataDriverEh</code> or <code v-pre>TADODataDriverEh</code> components (we will name them as <code v-pre>TXXXDataDriverEh</code>) allow to work with database without big number of tunings.</p>
<p>For <code v-pre>TXXXDataDriverEh</code> it is sufficiently to set database object property (For <code v-pre>TBDEDataDriverEh</code> it is a Database property of <code v-pre>TDatabase</code> type).</p>
<p><code v-pre>TSQLDataDriverEh</code> does not have database object property. To force it works is sufficiently to write <code v-pre>DefaultSQLDataDriverResolver</code>.</p>
<p><code v-pre>OnExecuteCommand</code> event once to execute queries on server, and assign <code v-pre>DefaultSQLDataDriverResolver.ServerSpecOperations</code>  property by the object of <code v-pre>TServerSpecOperationsEh</code> type to process some specific server operations. <code v-pre>DefaultSQLDataDriverResolver</code> is not visual object, so you have to assign an event and property in the program, for example in the <code v-pre>OnCreate</code> event of your main form. It is possible to change access Engine to database quickly when you use <code v-pre>TSQLDataDriverEh</code>. It is sufficiently rewrite global event  - <code v-pre>DefaultSQLDataDriverResolver.OnExecuteCommand</code> only.</p>
<p><code v-pre>TSQLDataDriverEh</code> and <code v-pre>TXXXDataDriverEh</code> works very similar at design-time. When <code v-pre>TSQLDataDriverEh</code> component editor is opening you can choose one of design-time types of the database accesses that built-over <code v-pre>BDE</code>, <code v-pre>ADO</code>, <code v-pre>IBX</code> and <code v-pre>DBX</code> engines. It  is not necessarily that the access engine that you use at design-time will be same as you write in <code v-pre>DefaultSQLDataDriverResolver.OnExecuteCommand</code> event.</p>
</div></template>


