<template><div><h1 id="master-detail-relations" tabindex="-1"><a class="header-anchor" href="#master-detail-relations" aria-hidden="true">#</a> Master/detail relations</h1>
<p><code v-pre>Master/detail</code> relation is a working mode of two datasets when all visible records of one dataset (DetailDataSet) always correspond to one record of other dataset (MasterDataSet). In time of moving in <code v-pre>MasterDataSet</code> the <code v-pre>DetailDataSet</code> will recreate or filters records so that they will correspond to <code v-pre>MasterDataSet</code> record. The correspondence is adjusted using <code v-pre>MasterFields</code> and <code v-pre>KeyFields</code> properties of <code v-pre>DetailDataSet</code>. <code v-pre>DetailDataSet</code> always show only the records, which values of the field/fields defined by <code v-pre>MasterFields</code> property is equal to values of the fields defined by <code v-pre>MasterFields</code> property of the current record of <code v-pre>MasterDataSet</code>.</p>
<p><code v-pre>TMemTableEh</code> allows to create a master/detail relations on the client side &quot;mdsOnSelfEh&quot; (by filtering record) or on DataProvider &quot;mdsOnProviderEh&quot; (by recreating list of records in DetailDataSet when record in MasterDataset is changed).</p>
<p>To adjust <code v-pre>TMemTableEh</code> in the master/detail mode use next properties: <code v-pre>MasterSource</code>, <code v-pre>MasterFields</code>, <code v-pre>KeyFields</code>, <code v-pre>MasterDetailSide</code>.</p>
<p>When <code v-pre>MasterDetailSide</code> is  <code v-pre>mdsOnSelfEh</code>, <code v-pre>TMemTableEh</code> will filter records by <code v-pre>DetailFields</code> fields using values of <code v-pre>MasterDataSet</code>[MasterFields] fields. When <code v-pre>MasterDetailSide</code> is <code v-pre>mdsOnProviderEh</code>, <code v-pre>DetailDataSet</code> will reopen itself, assigning parameters from <code v-pre>MasterDataSet</code> [MasterFields]. On opening it will pass parameters to <code v-pre>DataDriver</code>. In the <code v-pre>mdsOnProviderEh</code> mode the <code v-pre>DetailFields</code> are not used.</p>
<p>The third state of working &quot;mdsOnSelfAfterProviderEh&quot; is a combination of two preceding. Upon first moving to record in <code v-pre>MasterDataSet</code> the <code v-pre>DetailDataSet</code> gets records from <code v-pre>DataDriver</code>, sending him parameters with values, assigned from MasterSource[MasterFields] and add received records in its internal array of record. Upon next moving on same record in <code v-pre>MasterDataSet</code> the <code v-pre>DetailDataSet</code> will always only filter records locally.</p>
</div></template>


