export const data = JSON.parse("{\"key\":\"v-2dff405e\",\"path\":\"/EhLibDoc/27-tmemtableeh-component/05-working-with-auto-increment-fields.html\",\"title\":\"Working with AutoIncrement fields\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"TMemTableEh has an AutoIncrement property with InitValue and Step subproperties to work with fields which values are generated by automatic sequence numbers. For such fields pro...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/online-help-vuepress-hope/EhLibDoc/27-tmemtableeh-component/05-working-with-auto-increment-fields.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"EhLib.VCL Developer’s guide\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Working with AutoIncrement fields\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"TMemTableEh has an AutoIncrement property with InitValue and Step subproperties to work with fields which values are generated by automatic sequence numbers. For such fields pro...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}]]},\"excerpt\":\"\",\"headers\":[],\"readingTime\":{\"minutes\":0.73,\"words\":220},\"filePathRelative\":\"EhLibDoc/27-tmemtableeh-component/05-working-with-auto-increment-fields.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
