<template><div><h1 id="brief-description-of-tdbgrideh" tabindex="-1"><a class="header-anchor" href="#brief-description-of-tdbgrideh" aria-hidden="true">#</a> Brief description of TDBGridEh</h1>
<p><img src="@source/images/brief-description-of-tdbgrideh-01.png" alt="" loading="lazy"></p>
<p><code v-pre>TDBGridEh</code> displays and manipulates records from a dataset in a tabular grid.</p>
<p><code v-pre>TDBGridEh</code> is very similar to the standard TDBGrid component, but <code v-pre>TDBGridEh</code> does not inherit from TDBGrid or TCustomDBGrid.
The <code v-pre>TDBGridEh</code> inheritance tree looks like this:</p>
<p><code v-pre>TWinControl</code><br>
 <code v-pre>TCustomControl</code><br>
  <code v-pre>TCustomControlEh</code><br>
   <code v-pre>TCustomGridEh</code><br>
    <code v-pre>TCustomDBAxisGridEh</code><br>
     <code v-pre>TCustomDBGridEh</code></p>
<p><code v-pre>TDBGridEh</code> supports all the features of the <code v-pre>TDBGrid</code> component and also includes many additional features.</p>
<p>Some features of <code v-pre>TDBGridEh</code> only work when the grid is connected to a DataSet of type <code v-pre>TMemTableEh</code>. <code v-pre>TMemTableEh</code> is a <code v-pre>DataSet</code> that contains all the records in the computer's memory and is not connected directly to the database. TMemTableEh can be connected to other DataSets that can connect to the database. When working in conjunction with <code v-pre>TDBGridEh</code>-<code v-pre>TMemTableEh</code>-<code v-pre>TDataSetDataDriverEh</code>-<code v-pre>&lt;Your Dataset&gt;</code>, you will be able to work in the database and use all the features of <code v-pre>TDBGridEh</code> that it has when working with <code v-pre>TMemTableEh</code>.</p>
<p>When <code v-pre>TDBGridEh</code> is connected to <code v-pre>TMemTableEh</code>, then <code v-pre>TDBGridEh</code> has the following additional features such as:</p>
<ul>
<li>Ability to scroll the grid through a vertical scrollbar without changing the current record</li>
<li>Ability to create virtual group entries that appear as one wide entry in the grid. Group entries are created based on the repeated values of entries in a particular column.</li>
<li>Possibility to build a list of unique values in drop-down filtering lists.</li>
<li>Possibility to display data in the form of a tree. The tree structure is configured in the TMemTableEh component.</li>
</ul>
<p><code v-pre>TDBGridEh</code> does not store data in itself, it only displays the data of a TDataSet via a TDataLink object. Each DataSet component has an internal TDataLink object. You can connect <code v-pre>TDBGridEh</code> to a DataSet using an additional <code v-pre>TDataSource</code> object and the <code v-pre>TDBGridEh.DataSource</code> property. By itself, the intermediate TDataSource object carries little semantic load when interacting with <code v-pre>DBGridEh</code> and <code v-pre>DataSet</code>. It will rarely be mentioned in the documentation. If you have already used the TStringGrid component, you may have noticed that the data displayed in <code v-pre>TStringGrid</code> and <code v-pre>TDBGridEh</code> are very similar, but the mechanisms that are used to display data in <code v-pre>TStringGrid</code> and <code v-pre>TDBGridEh</code> are completely different. In <code v-pre>TStringGrid</code> the total number of grid rows is equal to the number of data rows in the array, while in <code v-pre>TDBGridEh</code> (and <code v-pre>TDBGrid</code>) the number of rows is never greater than the number of visible rows. While the vertical <code v-pre>ScrollBar</code> can display position relative to the total number of records in the DataSet, it takes its position data not from the grid's cell array, but directly from the <code v-pre>DataSet</code> (<code v-pre>DataSet.RecNo</code>). A similar feature or flaw has been fixed in the <code v-pre>DataSet</code> of the <code v-pre>TMemTableEh</code> type, but, in general, it is preserved for other types of DataSets that you will work with.</p>
<p><code v-pre>TDataSet</code> does not allow you to work with data as with an array of data, for example, it is impossible to immediately get the field value by the record index. Also, some types of DataSets don't even have the concept of a record number (<code v-pre>DataSet.RecNo</code>). In such DataSets, we can only know when we are at the beginning, or at the end of the DataSet, or somewhere in between, and in this case, the <code v-pre>DBGrid</code> only shows a vertical ScrollBar in 3 positions (in <code v-pre>TDBGridEh</code> to work with such DataSets' You can activate the <code v-pre>SumList</code> object and set the <code v-pre>SumList.VirtualRecords</code> property to <code v-pre>True</code>). To be able to display multiple records at the same time, the <code v-pre>TDataLink</code> object uses a record buffer window with fast read-only access. <code v-pre>DBGrid</code> takes advantage of this <code v-pre>DataLink</code> feature and sets the size of the record buffer window to the number of possible visible grid rows. <code v-pre>DataLink</code> does not allow to define from what record in <code v-pre>DataSet</code> this buffer is filled. The <code v-pre>DataLink</code> itself scrolls the contents of the record buffer window as we move through the <code v-pre>DataSet</code> (<code v-pre>Next</code>, <code v-pre>Prior</code>) so that the active record always remains inside the record buffer window. This is the reason why the active entry changes position when users change the <code v-pre>ScrollBar</code> position with the mouse.</p>
</div></template>


