<template><div><h1 id="save-restore-the-state-of-the-columns-in-the-ini-file-and-the-registry" tabindex="-1"><a class="header-anchor" href="#save-restore-the-state-of-the-columns-in-the-ini-file-and-the-registry" aria-hidden="true">#</a> Save / restore the state of the columns in the INI-file and the Registry</h1>
<p>Save rows settings to INI file or Registry</p>
<div class="language-pascal line-numbers-mode" data-ext="pascal"><pre v-pre class="language-pascal"><code><span class="token keyword">procedure</span> SaveRowsLayout<span class="token punctuation">(</span>ACustIni<span class="token punctuation">:</span> TCustomIniFile<span class="token punctuation">;</span> <span class="token keyword">const</span> Section<span class="token punctuation">:</span> <span class="token keyword">String</span><span class="token punctuation">)</span><span class="token punctuation">;</span>    
<span class="token keyword">procedure</span> SaveRowsLayout<span class="token punctuation">(</span>ARegIni<span class="token punctuation">:</span> TRegIniFile<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">procedure</span> SaveRowsLayoutIni<span class="token punctuation">(</span><span class="token keyword">const</span> IniFileName<span class="token punctuation">:</span> <span class="token keyword">String</span><span class="token punctuation">;</span> 
  <span class="token keyword">const</span> Section<span class="token punctuation">:</span> <span class="token keyword">String</span><span class="token punctuation">;</span> DeleteSection<span class="token punctuation">:</span> Boolean<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>The methods store the following Rows properties TFieldRowEh.Index, TFieldRowEh.RowLines, TFieldRowEh.Visible in an INI file or Registry</p>
<p>Save rows settings and grid layout to INI file or Registry</p>
<div class="language-pascal line-numbers-mode" data-ext="pascal"><pre v-pre class="language-pascal"><code>    <span class="token keyword">procedure</span> SaveGridLayout<span class="token punctuation">(</span>ACustIni<span class="token punctuation">:</span> TCustomIniFile<span class="token punctuation">;</span> 
      <span class="token keyword">const</span> Section<span class="token punctuation">:</span> <span class="token keyword">String</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
    <span class="token keyword">procedure</span> SaveGridLayout<span class="token punctuation">(</span>ARegIni<span class="token punctuation">:</span> TRegIniFile<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">procedure</span> SaveGridLayoutIni<span class="token punctuation">(</span><span class="token keyword">const</span> IniFileName<span class="token punctuation">:</span> <span class="token keyword">String</span><span class="token punctuation">;</span> 
      <span class="token keyword">const</span> Section<span class="token punctuation">:</span> <span class="token keyword">String</span><span class="token punctuation">;</span> DeleteSection<span class="token punctuation">:</span> Boolean<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Methods stores the settings for the rows described above, as well as the Grid.LabelColWidth property.</p>
<p>Load rows settings from an Ini file or Registry. The properties that will be loaded are set using the RestoreParams parameter.</p>
<div class="language-pascal line-numbers-mode" data-ext="pascal"><pre v-pre class="language-pascal"><code><span class="token keyword">procedure</span> RestoreRowsLayout<span class="token punctuation">(</span>ACustIni<span class="token punctuation">:</span> TCustomIniFile<span class="token punctuation">;</span> 
  <span class="token keyword">const</span> Section<span class="token punctuation">:</span> <span class="token keyword">String</span><span class="token punctuation">;</span> 
  RestoreParams<span class="token punctuation">:</span> TRowEhRestoreParams<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">procedure</span> RestoreRowsLayout<span class="token punctuation">(</span>ARegIni<span class="token punctuation">:</span> TRegIniFile<span class="token punctuation">;</span> 
  RestoreParams<span class="token punctuation">:</span> TRowEhRestoreParams<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">procedure</span> RestoreRowsLayoutIni<span class="token punctuation">(</span><span class="token keyword">const</span> IniFileName<span class="token punctuation">:</span> <span class="token keyword">String</span><span class="token punctuation">;</span> 
  <span class="token keyword">const</span> Section<span class="token punctuation">:</span> <span class="token keyword">String</span><span class="token punctuation">;</span> 
  RestoreParams<span class="token punctuation">:</span> TRowEhRestoreParams<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Load rows settings and grid layout  from an Ini file or Registry. The properties that will be loaded are set using the RestoreParams parameter.</p>
<div class="language-pascal line-numbers-mode" data-ext="pascal"><pre v-pre class="language-pascal"><code><span class="token keyword">procedure</span> RestoreGridLayout<span class="token punctuation">(</span>ARegIni<span class="token punctuation">:</span> TCustomIniFile<span class="token punctuation">;</span> 
  <span class="token keyword">const</span> Section<span class="token punctuation">:</span> <span class="token keyword">String</span><span class="token punctuation">;</span> 
  RestoreParams<span class="token punctuation">:</span> TDBVertGridEhRestoreParams<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">procedure</span> RestoreGridLayout<span class="token punctuation">(</span>ARegIni<span class="token punctuation">:</span> TRegIniFile<span class="token punctuation">;</span> 
  RestoreParams<span class="token punctuation">:</span> TDBVertGridEhRestoreParams<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">procedure</span> RestoreGridLayoutIni<span class="token punctuation">(</span><span class="token keyword">const</span> IniFileName<span class="token punctuation">:</span> <span class="token keyword">String</span><span class="token punctuation">;</span> 
  <span class="token keyword">const</span> Section<span class="token punctuation">:</span> <span class="token keyword">String</span><span class="token punctuation">;</span> 
  RestoreParams<span class="token punctuation">:</span> TDBVertGridEhRestoreParams<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


