<template><div><h1 id="showing-bitmaps-in-data-cells-depending-on-the-field-values" tabindex="-1"><a class="header-anchor" href="#showing-bitmaps-in-data-cells-depending-on-the-field-values" aria-hidden="true">#</a> Showing bitmaps in data cells depending on the field values</h1>
<p><code v-pre>TDBGridEh</code> allows to show bitmaps from <code v-pre>TImageList</code> component depending on the field values. In order to show bitmaps you need fill list <code v-pre>Column.KeyList</code> property by the possible field values (every value in the separated line) and set <code v-pre>Column.ImageList</code> property by the <code v-pre>TImageList</code> control that has the bitmaps. Every image in <code v-pre>ImageList</code> corresponds to the string line in the <code v-pre>KeyList</code> property. You can also set <code v-pre>Column.NotInKeyListIndex</code> property to the index of bitmap that will be shown if the field's value does not correspond to any value in the <code v-pre>KeyList</code> (for instance you can set index of image for <code v-pre>Null</code> field value). At run time you can’t edit cells with bitmaps. Use <code v-pre>SPACE</code> key or mouse click to set value from next line of <code v-pre>Column.KeyList</code> to the field. Use <code v-pre>Shift+SPACE</code> key or <code v-pre>Shift+Mouse</code> click to set value from previous line <code v-pre>Column.KeyList</code>. You can also set <code v-pre>Column.DblClickNextval</code> to <code v-pre>True</code> to allow changing values in cell by double mouse clicking.</p>
<p><img src="@source/images/DBGridEh.ShowImageAndText.png" alt="" loading="lazy"></p>
<p>Use <code v-pre>Column.ShowImageAndText</code> property to allow display text and picture in the cell. When <code v-pre>Column.ShowImageAndText = False</code> and <code v-pre>Column.ImageList</code> is assigned then grid will draw only picture from <code v-pre>ImageList</code>.
If the next properties are filled: <code v-pre>Column.ImageList</code>, <code v-pre>Column.KeyList</code> <code v-pre>Column.PickList</code> and <code v-pre>Column</code>.<code v-pre>ShowImageAndText = True</code>, then each column cell will work as combobox <code v-pre>KeyList</code> type and a each entry cell will show a picture of the <code v-pre>ImageList</code>.
Use the event <code v-pre>TColumnEh.OnGetCellParams</code> to specify a particular image index for pictures from <code v-pre>ImageList</code>. In the event handler, set <code v-pre>Params.ImageIndex</code> parameter value depending on the values of the fields of the current record, or other conditions.</p>
</div></template>


