<template><div><h1 id="values-in-table-cells-property-cells" tabindex="-1"><a class="header-anchor" href="#values-in-table-cells-property-cells" aria-hidden="true">#</a> Values in table cells (Property Cells)</h1>
<p>Use the two-dimensional array property <code v-pre>Sheet.Cells</code> to set cell values.</p>
<p>The array does not require adding cells to expand the size of the array. The array elements are created automatically when accessed.</p>
<p>The cell values are set by the <code v-pre>Variant</code> property Value. The property supports numeric, string, boolean data types, and the DateTime type for specifying the date and time.</p>
<p>Below is an example of setting table values</p>
<div class="language-pascal" data-ext="pascal"><pre v-pre class="language-pascal"><code>Sheet<span class="token punctuation">.</span>Cells<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> i <span class="token operator">+</span> <span class="token number">4</span><span class="token punctuation">]</span><span class="token punctuation">.</span>Value <span class="token operator">:=</span> DBGridEh1<span class="token punctuation">.</span>Columns<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>Field<span class="token punctuation">.</span>Value<span class="token punctuation">;</span>
Sheet<span class="token punctuation">.</span>Cells<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> i <span class="token operator">+</span> <span class="token number">4</span><span class="token punctuation">]</span><span class="token punctuation">.</span>Value <span class="token operator">:=</span> DBGridEh1<span class="token punctuation">.</span>Columns<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">.</span>Field<span class="token punctuation">.</span>Value<span class="token punctuation">;</span>
Sheet<span class="token punctuation">.</span>Cells<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">,</span> i <span class="token operator">+</span> <span class="token number">4</span><span class="token punctuation">]</span><span class="token punctuation">.</span>Value <span class="token operator">:=</span> DBGridEh1<span class="token punctuation">.</span>Columns<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">.</span>Field<span class="token punctuation">.</span>Value<span class="token punctuation">;</span>
</code></pre></div><p>In addition to values, a cell can also contain a formula. Use the <code v-pre>Formula</code> property to define the formula.
Below is an example of setting a formula for one cell of a table</p>
<div class="language-pascal" data-ext="pascal"><pre v-pre class="language-pascal"><code>Sheet<span class="token punctuation">.</span>Cells<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> i<span class="token operator">+</span><span class="token number">4</span><span class="token punctuation">]</span><span class="token punctuation">.</span>Formula <span class="token operator">:=</span> <span class="token string">'SUM(E5:'</span> <span class="token operator">+</span> <span class="token string">'E'</span> <span class="token operator">+</span> IntToStr<span class="token punctuation">(</span>i<span class="token operator">+</span><span class="token number">4</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">')'</span><span class="token punctuation">;</span>
</code></pre></div><p><code v-pre>TXlsMemFileEh</code> class does not perform formula cell calculations. Setting the <code v-pre>Formula</code> property does not change the <code v-pre>Value</code> property.</p>
<p>However, if you create a file that you plan to open in <code v-pre>MS Excel</code>, then when you open the file in MS Excel, the user will see the calculated data, because <code v-pre>MS Excel</code> recalculates the value of formulas when opening a file.</p>
</div></template>


