export const data = JSON.parse("{\"key\":\"v-2afa5f60\",\"path\":\"/EhLibDoc/04-list-of-components-and-classes.html\",\"title\":\"List of components and classes\",\"lang\":\"en-US\",\"frontmatter\":{\"//icon\":\"article\",\"title\":\"List of components and classes\",\"description\":\"Data Grids The main and most sophisticated component of the library. It provides all functionality of TDBGrid and adds several new features as follows:\\rAllows to select records,...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/online-help-vuepress-hope/EhLibDoc/04-list-of-components-and-classes.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"EhLib.VCL Developer’s guide\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"List of components and classes\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Data Grids The main and most sophisticated component of the library. It provides all functionality of TDBGrid and adds several new features as follows:\\rAllows to select records,...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"Data Grids\",\"slug\":\"data-grids\",\"link\":\"#data-grids\",\"children\":[]},{\"level\":2,\"title\":\"Edit controls\",\"slug\":\"edit-controls\",\"link\":\"#edit-controls\",\"children\":[]},{\"level\":2,\"title\":\"Printing, Preview, Export to Pdf\",\"slug\":\"printing-preview-export-to-pdf\",\"link\":\"#printing-preview-export-to-pdf\",\"children\":[]},{\"level\":2,\"title\":\"DataSet\",\"slug\":\"dataset\",\"link\":\"#dataset\",\"children\":[]},{\"level\":2,\"title\":\"Data provider components for TMemTableEh\",\"slug\":\"data-provider-components-for-tmemtableeh\",\"link\":\"#data-provider-components-for-tmemtableeh\",\"children\":[]},{\"level\":2,\"title\":\"Components for consolidated data analysis\",\"slug\":\"components-for-consolidated-data-analysis\",\"link\":\"#components-for-consolidated-data-analysis\",\"children\":[]},{\"level\":2,\"title\":\"Components for planning and visual interactive event management\",\"slug\":\"components-for-planning-and-visual-interactive-event-management\",\"link\":\"#components-for-planning-and-visual-interactive-event-management\",\"children\":[]},{\"level\":2,\"title\":\"Components for exporting/importing data to/from DataSet from/to a text file.\",\"slug\":\"components-for-exporting-importing-data-to-from-dataset-from-to-a-text-file\",\"link\":\"#components-for-exporting-importing-data-to-from-dataset-from-to-a-text-file\",\"children\":[]},{\"level\":2,\"title\":\"Other components and classes\",\"slug\":\"other-components-and-classes\",\"link\":\"#other-components-and-classes\",\"children\":[]}],\"readingTime\":{\"minutes\":7.69,\"words\":2307},\"filePathRelative\":\"EhLibDoc/04-list-of-components-and-classes.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
