<template><div><h1 id="list-of-library-components-and-classes" tabindex="-1"><a class="header-anchor" href="#list-of-library-components-and-classes" aria-hidden="true">#</a> List of library components and classes</h1>
<h2 id="data-grids" tabindex="-1"><a class="header-anchor" href="#data-grids" aria-hidden="true">#</a> Data Grids</h2>
<h4 id="tdbgrideh-control" tabindex="-1"><a class="header-anchor" href="#tdbgrideh-control" aria-hidden="true">#</a> <img src="@source/images/components/DBGridEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/01-content.html">TDBGridEh control</RouterLink></h4>
<p>The main and most sophisticated component of the library.
It provides all functionality of TDBGrid and adds several new features as follows:</p>
<ul>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/45-multiselect.html">Allows to select records, columns and rectangle areas</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/32-customizing-grid-title.html#complex-titles">Provides special titles that can cover several or all columns</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/35-customizing-grid-footer.html">Can have a footer that is able to show sum/count/other field values</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/08-moving-and-resizing-columns-in-the-grid.html">Allows to resize column automatically to fit grid width equal to client width</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/14-data-row-height.html">Has an ability to change row height and title height</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/32-customizing-grid-title.html#complex-titles">Allows automatic broken of a single line long title and data rows to a multiline</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/32-customizing-grid-title.html">Allows title to act as button and, optionally show a sort marker</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/30-adjusting-grid-for-sorting-data.html">Allows to mark titles by sortmarking sings automatically and sort data in DataSet</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/11-formatting-the-data-in-the-grid.html">Allows to truncate long text with ellipsis in cells</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/05-types-of-columns-and-data-types-in-columns/04-configure-the-lookup-relationship-in-grid-columns.html">Allows lookup list to show several fields</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/05-types-of-columns-and-data-types-in-columns/04-configure-the-lookup-relationship-in-grid-columns.html">Have an ability to make an incremental search in lookup fields</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/44-frozen-zone.html">Can have frozen nonscrollable columns</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/05-types-of-columns-and-data-types-in-columns/10-dropdown-calendar.html">Allows to show DateTime picker for TDateField and TDateTimeField</RouterLink></li>
<li>Allows to show bitmaps from TImageList depending on field value</li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/24-customizing-scrollbars.html">Allows to hide and track horizontal or vertical scrollbars</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/09-visibility-columns-in-the-grid.html">Allows to hide columns</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/49-other-features-and-events.html">Allows to show 3D frame for frozen, footer and data rows</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/05-types-of-columns-and-data-types-in-columns/09-draw-memo-fields.html">Allows to draw memo fields</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/11-formatting-the-data-in-the-grid.html">Can show multiline inplace editor</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/24-customizing-scrollbars.html">Can have a proportional scrolling for DadaSets independently of dataset’s sequencing</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/05-types-of-columns-and-data-types-in-columns/05-checkboxes.html">Allows to show checkboxes automatically for Boolean fields. Allows to show checkboxes for other type of fields</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/43-storing-settings.html">Has procedures to save and restore layout (visible columns, columns order, columns width, sortmarkers, row height) in/from registry or ini file</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/36-hints-and-tooltips.html">Allows to show hint (ToolTips) for text that don't fit in the cell</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/04-import-export-tdbgrideh-data-to-from-various-formats.html">Allows to export data to Text, Csv, HTML, RTF, XLS and internal formats</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/04-import-export-tdbgrideh-data-to-from-various-formats.html">Allows to import data from Text and internal formats</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/30-adjusting-grid-for-sorting-data.html">Can sort data in various datasets</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/31-adjusting-grid-for-filtering-data.html">Can filter data in various datasets</RouterLink></li>
<li><RouterLink to="/EhLibDoc/10-using-tdbgrideh-component/20-working-with-data-grouping-mode.html">Allows to group data in memory using columns as a grouping criterions</RouterLink></li>
</ul>
<h4 id="tdbvertgrideh-control" tabindex="-1"><a class="header-anchor" href="#tdbvertgrideh-control" aria-hidden="true">#</a> <img src="@source/images/components/TDBVertGridEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/12-dbvertgrideh-component/01-dbvertgrideh-component.html">TDBVertGridEh control</RouterLink></h4>
<p>TDBVertGridEh сomponent is a Vertical Grid.</p>
<p>The component is used to display and edit a single record DataSet in a vertical orientation. The data is displayed in two columns. The first column displays the names of the fields in the second field values of the current record.</p>
<h2 id="edit-controls" tabindex="-1"><a class="header-anchor" href="#edit-controls" aria-hidden="true">#</a> Edit controls</h2>
<h4 id="tdblookupcomboboxeh-control" tabindex="-1"><a class="header-anchor" href="#tdblookupcomboboxeh-control" aria-hidden="true">#</a> <img src="@source/images/components/TDBLookupComboboxEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/14-edit-controls/16-tdblookupcomboboxeh-control.html">TDBLookupComboboxEh control</RouterLink></h4>
<p>TDBLookupComboBox represents a combo box that identifies a set of field values in one dataset with a corresponding set of values from another dataset.</p>
<h4 id="tdbediteh-control" tabindex="-1"><a class="header-anchor" href="#tdbediteh-control" aria-hidden="true">#</a> <img src="@source/images/components/TDBEditEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/14-edit-controls/01-edit-controls.html">TDBEditEh control</RouterLink></h4>
<p>represents a single or multi-line edit control that can display and edit data of field in a dataset or can work as non data-aware edit control.</p>
<h4 id="tdbdatetimeediteh-control" tabindex="-1"><a class="header-anchor" href="#tdbdatetimeediteh-control" aria-hidden="true">#</a> <img src="@source/images/components/TDBDateTimeEditEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/14-edit-controls/08-tdbdatetimeediteh-control.html">TDBDateTimeEditEh control</RouterLink></h4>
<p>represents a single-line date or time edit control that can display and edit data of TDateTime fields in dataset or can work as a non data-aware edit control.</p>
<h4 id="tdbcomboboxeh-control" tabindex="-1"><a class="header-anchor" href="#tdbcomboboxeh-control" aria-hidden="true">#</a> <img src="@source/images/components/TDBComboBoxEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/14-edit-controls/10-tdbcomboboxeh-control.html">TDBComboBoxEh control</RouterLink></h4>
<p>represents a single or multi-line edit control that combines an edit box with a scrollable list and can display and edit a field in a dataset or can works as non data-aware combo edit control.</p>
<h4 id="tdbnumberediteh-control" tabindex="-1"><a class="header-anchor" href="#tdbnumberediteh-control" aria-hidden="true">#</a> <img src="@source/images/components/TDBNumberEditEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/14-edit-controls/09-tdbnumberediteh-control.html">TDBNumberEditEh control</RouterLink></h4>
<p>Represents a single-line number edit control that can display and edit a numeric field in a dataset or can work as non data-aware edit control.</p>
<h4 id="tdbmemoeh-control" tabindex="-1"><a class="header-anchor" href="#tdbmemoeh-control" aria-hidden="true">#</a> <img src="@source/images/components/TDBMemoEh-Icon.png" alt="" loading="lazy">   <RouterLink to="/EhLibDoc/14-edit-controls/11-tdbmemoeh-control.html">TDBMemoEh control</RouterLink></h4>
<p>The component is designed for editing multi-line text data.
The component can operate in Data-Aware mode (connected to DataSet), and can work as non data-aware edit control.</p>
<h4 id="tdbimageeh-control" tabindex="-1"><a class="header-anchor" href="#tdbimageeh-control" aria-hidden="true">#</a> <img src="@source/images/components/TDBImageEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/14-edit-controls/12-tdbimageeh-control.html">TDBImageEh control</RouterLink></h4>
<p>The component is designed for editing a graphic data.
The component can operate in Data-Aware mode (connected to DataSet), and can work as non data-aware edit control.</p>
<h4 id="tdbradiogroupeh-control" tabindex="-1"><a class="header-anchor" href="#tdbradiogroupeh-control" aria-hidden="true">#</a> <img src="@source/images/components/TDBRadioGroupEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/14-edit-controls/13-tdbradiogroupeh-control.html">TDBRadioGroupEh control</RouterLink></h4>
<p>The component is a set of selection flags (radiobuttons).
The component can operate in Data-Aware mode (connected to DataSet), and can work as non data-aware edit control.</p>
<h4 id="tdbrichediteh-control" tabindex="-1"><a class="header-anchor" href="#tdbrichediteh-control" aria-hidden="true">#</a> <img src="@source/images/components/TDBRichEditEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/14-edit-controls/14-tdbrichediteh-control.html">TDBRichEditEh control</RouterLink></h4>
<p>The component is designed for editing multi-line text data with the ability to format it as RichText.
The component can operate in Data-Aware mode (connected to DataSet), and can work as non data-aware edit control.</p>
<h2 id="printing-preview-export-to-pdf" tabindex="-1"><a class="header-anchor" href="#printing-preview-export-to-pdf" aria-hidden="true">#</a> Printing, Preview, Export to Pdf</h2>
<h4 id="tprintdbgrideh-component" tabindex="-1"><a class="header-anchor" href="#tprintdbgrideh-component" aria-hidden="true">#</a> <img src="@source/images/components/TPrintDBGridEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/11-printdbgrideh-component/01-content.html">TPrintDBGridEh component</RouterLink></h4>
<p>TPrintDBGridEh provides properties and routines for preview, print of TDBGridEh component. It also allows to export
TDBGridEh to pdf file.</p>
<h4 id="tpreviewbox-component" tabindex="-1"><a class="header-anchor" href="#tpreviewbox-component" aria-hidden="true">#</a> <img src="@source/images/components/TPreviewBox-Icon.png" alt="" loading="lazy">  [TPreviewBox component]</h4>
<p>TPreviewBox lets you to create a customizable runtime preview.</p>
<h4 id="tprinterpreview-class" tabindex="-1"><a class="header-anchor" href="#tprinterpreview-class" aria-hidden="true">#</a> <img src="@source/images/components/TClass-Icon.png" alt="" loading="lazy">  [TPrinterPreview class]</h4>
<p>TPrinterPreview lets you to record printable data in buffer for following output them on screen and to printer. TPrinterPreview have all functions and properties as in TPrinter object. You can use TPrinterPreview object similarly to TPrinter except some details. In TPrinter Printer.Canvas.Handle and Printer.Handle is the same but in TPrinterPreview PrinterPreview.Canvas.Handle represents the metafile in that is recored the data and PrinterPreview.Handle represents Printer.Handle. It means that you have to use PrinterPreview.Canvas.Handle for drawing operation (like DrawText, DrawTexteEx, e.t.c.) and use PrinterPreview.Handle for such functions as returning information about printer facilities (GetDeviceCaps, e.t.c.). Global function PrinterPreview returns default PrinterPreview object and shows data in the default preview form.</p>
<h4 id="tpdfprintereh-class" tabindex="-1"><a class="header-anchor" href="#tpdfprintereh-class" aria-hidden="true">#</a> <img src="@source/images/components/TClass-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/23-generating-pdf-files-using-the-printer-class.html">TPdfPrinterEh class</RouterLink></h4>
<p>The library has a global method - PdfPrintersEh.PdfPrinter for accessing a class of TPdfPrinterEh type with which you can generate Pdf files similar to how printed documents are generated using the global method - Printers.Printer.</p>
<h4 id="tvirtualprinter-class" tabindex="-1"><a class="header-anchor" href="#tvirtualprinter-class" aria-hidden="true">#</a> <img src="@source/images/components/TClass-Icon.png" alt="" loading="lazy">  [TVirtualPrinter class]</h4>
<p>The library has a global method - PrntsEh.VirtualPrinter of TVirtualPrinter type. PrntsEh.VirtualPrinter function allows to print graphic data on a printer. The function works similarly to the Vcl.Printers.Printer function from the VCL library and has additional features such as redirecting the print stream to a preview window (TPreviewBox) or to a Pdf file.</p>
<h2 id="dataset" tabindex="-1"><a class="header-anchor" href="#dataset" aria-hidden="true">#</a> DataSet</h2>
<h4 id="tmemtableeh-component" tabindex="-1"><a class="header-anchor" href="#tmemtableeh-component" aria-hidden="true">#</a> <img src="@source/images/components/TMemTableEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/27-tmemtableeh-component/01-tmemtableeh-component.html">TMemTableEh component</RouterLink></h4>
<p>It is a dataset that holds all data in memory. It can work as a standalone DataSet or receive data from other DataSets via the TDataDriverEh component.</p>
<h2 id="data-provider-components-for-tmemtableeh" tabindex="-1"><a class="header-anchor" href="#data-provider-components-for-tmemtableeh" aria-hidden="true">#</a> Data provider components for TMemTableEh</h2>
<h4 id="tdatadrivereh-component" tabindex="-1"><a class="header-anchor" href="#tdatadrivereh-component" aria-hidden="true">#</a> <img src="@source/images/components/TClass-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/28-tdatadrivereh-component.html">TDataDriverEh component</RouterLink></h4>
<p>Deliver records from the server or other DataSet to the TMemTableEh.
Deliver changed records from TMemTableEh back to the server.</p>
<h4 id="tdatasetdrivereh-component" tabindex="-1"><a class="header-anchor" href="#tdatasetdrivereh-component" aria-hidden="true">#</a> <img src="@source/images/components/TDataSetDriverEh-Icon.png" alt="" loading="lazy">  [TDataSetDriverEh component]</h4>
<p>It is a DataDriver that deliver records in TMemTableEh from other DataSet and deliver changed records from TMemTableEh back to the DataSet.</p>
<h4 id="tsqldatadrivereh-component" tabindex="-1"><a class="header-anchor" href="#tsqldatadrivereh-component" aria-hidden="true">#</a> <img src="@source/images/components/TSQLDataDriverEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/29-tsqldatadrivereh-component/01-content.html">TSQLDataDriverEh component</RouterLink></h4>
<p>It is a DataDriver that have properties for keeping five SQL expressions and parameters for querying data, removing, insertions, updating and refreshing records. TSQLDataDriverEh by itself can’t request data from server, but it can prepare parameters of the request and have a global event that programmer can write for transferring SQL expression to/from the server.</p>
<h4 id="tbdedatadrivereh-component" tabindex="-1"><a class="header-anchor" href="#tbdedatadrivereh-component" aria-hidden="true">#</a> <img src="@source/images/components/TBDEDataDriverEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/29-tsqldatadrivereh-component/02-tsqldatadrivereh-component.html">TBDEDataDriverEh component</RouterLink></h4>
<p>It is a DataDriver that interacts with the DB server using BDE connection.</p>
<h4 id="tibxdatadrivereh-component" tabindex="-1"><a class="header-anchor" href="#tibxdatadrivereh-component" aria-hidden="true">#</a> <img src="@source/images/components/TIBXDataDriverEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/29-tsqldatadrivereh-component/02-tsqldatadrivereh-component.html">TIBXDataDriverEh component</RouterLink></h4>
<p>It is a DataDriver that interacts with the DB server using IBX connection.</p>
<h4 id="tdbxdatadrivereh-component" tabindex="-1"><a class="header-anchor" href="#tdbxdatadrivereh-component" aria-hidden="true">#</a> <img src="@source/images/components/TDBXDataDriverEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/29-tsqldatadrivereh-component/02-tsqldatadrivereh-component.html">TDBXDataDriverEh component</RouterLink></h4>
<p>It is a DataDriver that interacts with the DB server using DBX connection.</p>
<h4 id="tadodatadrivereh-component" tabindex="-1"><a class="header-anchor" href="#tadodatadrivereh-component" aria-hidden="true">#</a> <img src="@source/images/components/TADODataDriverEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/29-tsqldatadrivereh-component/02-tsqldatadrivereh-component.html">TADODataDriverEh component</RouterLink></h4>
<p>It is a DataDriver that interacts with the DB server using ADO connection.</p>
<h4 id="tadoconnectionprovidereh-component" tabindex="-1"><a class="header-anchor" href="#tadoconnectionprovidereh-component" aria-hidden="true">#</a> <img src="@source/images/components/TADOConnectionProviderEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/29-tsqldatadrivereh-component/06-uisng-connection-provider.html">TADOConnectionProviderEh component</RouterLink></h4>
<p>Provides the interface between the component TADODataDriver and TADOConnection in Design-Time and Run-Time. Contains inbuilt TADOConnection component. Specifies the type of server data for the correct operation of additional server operations, such as getting the value of the incremental table fields after inserting record, etc.</p>
<h4 id="tdbxconnectionprovidereh-component" tabindex="-1"><a class="header-anchor" href="#tdbxconnectionprovidereh-component" aria-hidden="true">#</a> <img src="@source/images/components/TDBXConnectionProviderEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/29-tsqldatadrivereh-component/06-uisng-connection-provider.html">TDBXConnectionProviderEh component</RouterLink></h4>
<p>Provides the interface between TDBXDataDriver and TSQLConnection in Design-Time and Run-Time. Contains embedded TSQLConnection component. Specifies the type of server data for the correct operation of additional server operations, such as getting the value of the incremental table fields after inserting record, etc.</p>
<h4 id="tibxconnectionprovidereh-component" tabindex="-1"><a class="header-anchor" href="#tibxconnectionprovidereh-component" aria-hidden="true">#</a> <img src="@source/images/components/TIBXConnectionProviderEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/29-tsqldatadrivereh-component/06-uisng-connection-provider.html">TIBXConnectionProviderEh component</RouterLink></h4>
<p>Provides the interface between the component TIBXDataDriver and TIBDatabase in Design-Time and Run-Time. Contains built TIBDatabase component.
TBDEConnectionProviderEh component		
Provides the interface between the component TBDEDataDriver and TDatabase in Design-Time and Run-Time. Contains inbuilt TDatabase component. Specifies the type of server data for the correct operation of additional server operations, such as getting the value of the incremental table fields after inserting record, etc.</p>
<h2 id="components-for-consolidated-data-analysis" tabindex="-1"><a class="header-anchor" href="#components-for-consolidated-data-analysis" aria-hidden="true">#</a> Components for consolidated data analysis</h2>
<h4 id="tpivotdatasourceeh-component" tabindex="-1"><a class="header-anchor" href="#tpivotdatasourceeh-component" aria-hidden="true">#</a> <img src="@source/images/components/TPivotDataSourceEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/30-components-for-consolidated-data-analysis/01-components-for-consolidated-data-analysis.html">TPivotDataSourceEh component</RouterLink></h4>
<p>Downloads and store pivot data.</p>
<h4 id="tpivotgrideh-control" tabindex="-1"><a class="header-anchor" href="#tpivotgrideh-control" aria-hidden="true">#</a> <img src="@source/images/components/TPivotGridEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/30-components-for-consolidated-data-analysis/01-components-for-consolidated-data-analysis.html">TPivotGridEh control</RouterLink></h4>
<p>Component-control to display pivot data.</p>
<h4 id="tpivotgridtoolboxeh-control" tabindex="-1"><a class="header-anchor" href="#tpivotgridtoolboxeh-control" aria-hidden="true">#</a> <img src="@source/images/components/TPivotGridToolBoxEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/30-components-for-consolidated-data-analysis/01-components-for-consolidated-data-analysis.html">TPivotGridToolBoxEh control</RouterLink></h4>
<p>Component-control for configuration data structure and sections stored in the PivotDataSource component.</p>
<h2 id="components-for-planning-and-visual-interactive-event-management" tabindex="-1"><a class="header-anchor" href="#components-for-planning-and-visual-interactive-event-management" aria-hidden="true">#</a> Components for planning and visual interactive event management</h2>
<h4 id="tplannerdatasourceeh" tabindex="-1"><a class="header-anchor" href="#tplannerdatasourceeh" aria-hidden="true">#</a> <img src="@source/images/components/TPlannerDataSourceEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/31-components-for-planning-management/01-components-for-planning-and-event-management.html#component-tplannerdatasourceeh">TPlannerDataSourceEh</RouterLink></h4>
<p>The component is used to store event objects such as TPlannerDataItemEh.</p>
<h4 id="tplannercontroleh" tabindex="-1"><a class="header-anchor" href="#tplannercontroleh" aria-hidden="true">#</a> <img src="@source/images/components/TPlannerControlEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/31-components-for-planning-management/01-components-for-planning-and-event-management.html#component-tplannercontroleh">TPlannerControlEh</RouterLink></h4>
<p>The visual component-container TPlannerControlEh contains a set of visual components PlannerView.</p>
<h4 id="tplannercalendarpickereh" tabindex="-1"><a class="header-anchor" href="#tplannercalendarpickereh" aria-hidden="true">#</a> <img src="@source/images/components/TPlannerCalendarPickerEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/31-components-for-planning-management/01-components-for-planning-and-event-management.html#component-tplannercalendarpickereh">TPlannerCalendarPickerEh</RouterLink></h4>
<p>The visual component-calendar is designed to navigate through the days of the month.</p>
<h2 id="components-for-exporting-importing-data-to-from-dataset-from-to-a-text-file" tabindex="-1"><a class="header-anchor" href="#components-for-exporting-importing-data-to-from-dataset-from-to-a-text-file" aria-hidden="true">#</a> Components for exporting/importing data to/from DataSet from/to a text file.</h2>
<h4 id="tdatasettextexportereh-component" tabindex="-1"><a class="header-anchor" href="#tdatasettextexportereh-component" aria-hidden="true">#</a> <img src="@source/images/components/TDataSetTextExporterEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/33-components-for-uploading-data-set-text.html">TDataSetTextExporterEh component</RouterLink></h4>
<p>Component for uploading data from a DataSet to a text file for later downloading from it.</p>
<h4 id="tdatasettextimportereh-component" tabindex="-1"><a class="header-anchor" href="#tdatasettextimportereh-component" aria-hidden="true">#</a> <img src="@source/images/components/TDataSetTextImporterEh-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/33-components-for-uploading-data-set-text.html">TDataSetTextImporterEh component</RouterLink></h4>
<p>Component for downloading data from Text file to DataSet it.</p>
<h2 id="other-components-and-classes" tabindex="-1"><a class="header-anchor" href="#other-components-and-classes" aria-hidden="true">#</a> Other components and classes</h2>
<h4 id="dropdownforms-custom-drop-down-windows" tabindex="-1"><a class="header-anchor" href="#dropdownforms-custom-drop-down-windows" aria-hidden="true">#</a> <img src="@source/images/components/TClass-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/20-drop-down-forms.html">DropDownForms - custom drop-down windows</RouterLink></h4>
<p>The technology allows you to create a customizable drop-down windows that appears when user click on the button (EditButton) in TDBEditEh, TDBNumberEditEh, TInplaceEditor in DBGridEh etc. components.</p>
<h4 id="tdbsumlist-component" tabindex="-1"><a class="header-anchor" href="#tdbsumlist-component" aria-hidden="true">#</a> <img src="@source/images/components/TDBSumList-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/13-using-tdbsumlist-component.html">TDBSumList component</RouterLink></h4>
<p>TDBSumList is intended for calculating sums and amount of records in a TDataSet with dynamic changes. Component keeps a list of TDBSum objects, which contains types of group operations (Sum, Avg, Count, Min, Max) and name of fields which values need some calculation.</p>
<h4 id="txlsmemfileeh-class" tabindex="-1"><a class="header-anchor" href="#txlsmemfileeh-class" aria-hidden="true">#</a> <img src="@source/images/components/TClass-Icon.png" alt="" loading="lazy">  <RouterLink to="/EhLibDoc/32-txlsmemfileeh/00-content.html">TXlsMemFileEh class</RouterLink></h4>
<p>Allows you to create <code v-pre>Xlsx</code> files without the participation of installed <code v-pre>MSOffice</code> modules.</p>
</div></template>


