<template><div><h1 id="tsqldatadrivereh-component" tabindex="-1"><a class="header-anchor" href="#tsqldatadrivereh-component" aria-hidden="true">#</a> TSQLDataDriverEh component</h1>
<p><code v-pre>TSQLDataDriverEh</code> is a universal <code v-pre>DataDriver</code> that can interact with server using <code v-pre>SQL</code> commands.</p>
<p><code v-pre>TSQLDataDriverEh</code> have five objects of the <code v-pre>TSQLCommandEh</code> type: <code v-pre>SelectCommand</code>, <code v-pre>DeleteCommand</code>, <code v-pre>InsertCommand</code>, <code v-pre>UpdateCommand</code>, <code v-pre>GetrecCommand</code>.</p>
<p>Each object holds <code v-pre>SQL</code> expressions and parameters to execute command to get table data, delete record, insert record, update record and get one record. To execute commands <code v-pre>TSQLDataDriverEh</code> calls global event - <code v-pre>DefaultSQLDataDriverResolver.OnExecuteCommand</code>.</p>
<p>You should write this event to execute SQL expressions on the server and, if need, return <code v-pre>DataSet</code> to read data. When <code v-pre>TSQLDataDriverEh</code>  is used as provider of data, it takes records from DataSet created in <code v-pre>DefaultSQLDataDriverResolver.OnExecuteCommand</code> event and writes them in <code v-pre>TMemTableEh</code>. On the measure of the requirement it takes given current record, writes them in <code v-pre>TMemTableEh</code> and goes over to following record.</p>
<p>When <code v-pre>TSQLDataDriverEh</code> is used as handler of changes, it takes a changed record from <code v-pre>TMemTableEh</code>, and call <code v-pre>DefaultSQLDataDriverResolver.OnExecuteCommand</code> event sending <code v-pre>DeleteCommand</code>, <code v-pre>InsertCommand</code> or <code v-pre>UpdateCommand</code> as a parameter.</p>
<p>Using <code v-pre>TSQLDataDriverEh</code> it is possible change a type of the access to data. Suffice it to rewrite global event - <code v-pre>DefaultSQLDataDriverResolver.OnExecuteCommand</code>.</p>
<p><code v-pre>TSQLDataDriverEh</code> has a <code v-pre>SpecParams</code> property of <code v-pre>TStrings</code> type. You may use it to write the special values, which you can use in the <code v-pre>DefaultSQLDataDriverResolver.OnExecuteCommand</code> event. This event also is used by <code v-pre>TServerSpecOperationsEh</code> object when <code v-pre>DefaultSQLDataDriverResolver.ServerSpecOperations</code> property is assigned. List of special values depends of the type of <code v-pre>TServerSpecOperationsEh</code> object and values is filled similarly of description in the &quot;Characteristic TXXXDataDriverEh.SpecParams&quot; section.</p>
<p><code v-pre>DefaultSQLDataDriverResolver.ServerSpecOperations</code> property has a <code v-pre>TServerSpecOperationsEh</code> type. This object is intended to process the special operations before or after <code v-pre>ExecuteCommand</code> procedure is performed. <code v-pre>TServerSpecOperationsEh</code> is a base class for classes<br>
<code v-pre>TOracleSpecOperationsEh</code>, <code v-pre>TMSSQLSpecOperationsEh</code>, <code v-pre>TInterbaseSpecOperationsEh</code>, <code v-pre>TInfromixSpecOperationsEh</code>, <code v-pre>TDB2SpecOperationsEh</code>, <code v-pre>TSybaseSpecOperationsEh</code> and <code v-pre>TMSAccessSpecOperationsEh</code>.</p>
<p>Each Of these objects can process a <code v-pre>SpecParams</code> property in particular to get values of the autoincrement fields that is generated by the server.</p>
<p>On the name of the class it is possible to define a type of the server, for which class is intended.</p>
<p>For full functioning of <code v-pre>TSQLDataDriverEh</code> it is necessary to write <code v-pre>DefaultSQLDataDriverResolver.OnExecuteCommand</code> event to execute queries on the server and assign <code v-pre>DefaultSQLDataDriverResolver.ServerSpecOperations</code> property by the object that inherited from <code v-pre>TServerSpecOperationsEh</code> class.
Assigning a <code v-pre>ServerSpecOperations</code> property makes sense, if you execute operations of the insertion in tables that have autoincrement field (or sequence objects).</p>
<p>The typical code to adjust working of <code v-pre>TSQLDataDriverEh</code> can be look as follows:</p>
<div class="language-pascal" data-ext="pascal"><pre v-pre class="language-pascal"><code><span class="token comment">// Below code adjusts working of  TSQLDataDriverEh components in the whole Application to access </span>
<span class="token comment">// InderBase server via BDE Engine</span>
<span class="token keyword">uses</span> … DataDriverEh<span class="token punctuation">,</span> BDEDataDriverEh<span class="token punctuation">;</span>
<span class="token keyword">type</span>
  TMainForm <span class="token operator">=</span> <span class="token keyword">class</span><span class="token punctuation">(</span>TMainForm<span class="token punctuation">)</span>
    Database1<span class="token punctuation">:</span> TDatabase<span class="token punctuation">;</span>
    SQLDataDriverEh<span class="token punctuation">:</span> TSQLDataDriverEh<span class="token punctuation">;</span>
…
<span class="token keyword">procedure</span> TMainForm<span class="token punctuation">.</span>FormCreate<span class="token punctuation">(</span>Sender<span class="token punctuation">:</span> TObject<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">begin</span>
  DefaultSQLDataDriverResolver<span class="token punctuation">.</span>OnExecuteCommand <span class="token operator">:=</span> OnExecuteSQLCommand<span class="token punctuation">;</span>
  DefaultSQLDataDriverResolver<span class="token punctuation">.</span>ServerSpecOperations <span class="token operator">:=</span> TInterbaseSpecOperationsEh<span class="token punctuation">.</span>Create<span class="token punctuation">;</span>
<span class="token keyword">end</span><span class="token punctuation">;</span>

<span class="token keyword">procedure</span> TMainForm<span class="token punctuation">.</span>FormDestroy<span class="token punctuation">(</span>Sender<span class="token punctuation">:</span> TObject<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">begin</span>
  DefaultSQLDataDriverResolver<span class="token punctuation">.</span>ServerSpecOperations<span class="token punctuation">.</span>Free<span class="token punctuation">;</span>
  DefaultSQLDataDriverResolver<span class="token punctuation">.</span>ServerSpecOperations <span class="token operator">:=</span> <span class="token keyword">Nil</span><span class="token punctuation">;</span>
<span class="token keyword">end</span><span class="token punctuation">;</span>

<span class="token keyword">function</span> TMainForm<span class="token punctuation">.</span>OnExecuteSQLCommand<span class="token punctuation">(</span>SQLDataDriver<span class="token punctuation">:</span> TCustomSQLDataDriverEh<span class="token punctuation">;</span>
  Command<span class="token punctuation">:</span> TCustomSQLCommandEh<span class="token punctuation">;</span> <span class="token keyword">var</span> Cursor<span class="token punctuation">:</span> TDataSet<span class="token punctuation">;</span> <span class="token keyword">var</span> FreeOnEof<span class="token punctuation">,</span>
  Processed<span class="token punctuation">:</span> Boolean<span class="token punctuation">)</span><span class="token punctuation">:</span> Integer<span class="token punctuation">;</span>
<span class="token keyword">begin</span>
  <span class="token keyword">Result</span> <span class="token operator">:=</span> DefaultExecuteBDECommandEh<span class="token punctuation">(</span>SQLDataDriver<span class="token punctuation">,</span> Command<span class="token punctuation">,</span>
    Cursor<span class="token punctuation">,</span> FreeOnEof<span class="token punctuation">,</span> Processed<span class="token punctuation">,</span> Database1<span class="token punctuation">.</span>DatabaseName<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">end</span><span class="token punctuation">;</span>
</code></pre></div><p><code v-pre>TSQLDataDriverEh</code> is a base class for <code v-pre>TBDEDataDriverEh</code>, <code v-pre>TIBXDataDriverEh</code>, <code v-pre>TDBXDataDriverEh</code> and <code v-pre>TADODataDriverEh</code>. These objects overwrite <code v-pre>ExecuteCommand</code> procedure and them can execute <code v-pre>SQL</code> expressions on the server and if need returns DataSet to read data. When <code v-pre>SQL</code> commands is called, it creates DataSet with type of corresponding type of the access to data. For TBDEDataDriverEh it is a TQuery, for <code v-pre>TIBXDataDriverEh</code> it is a <code v-pre>TIBXQuery</code> and so on. Furthermore, <code v-pre>TBDEDataDriverEh</code>, <code v-pre>TIBXDataDriverEh</code>, <code v-pre>TDBXDataDriverEh</code> can define <code v-pre>TServerSpecOperationsEh</code> object automatically. For <code v-pre>TADODataDriverEh</code> it is need to assign <code v-pre>DefaultSQLDataDriverResolver</code>. <code v-pre>ServerSpecOperations</code> because ADO technology does not allow to define a type of the server.</p>
<p>TSQLDataDriverEh have the next events:
<code v-pre>OnExecuteCommand</code>
write this event to execute SQL expression. You can call <code v-pre>TCustomSQLDataDriverEh.DefaultExecuteCommand</code> method to process this event by default. By default <code v-pre>TCustomSQLDataDriverEh.DefaultExecuteCommand</code> calls <code v-pre>DefaultSQLDataDriverResolver.ExecuteCommand</code> method, which, in turn, call <code v-pre>DefaultSQLDataDriverResolver.OnExecuteCommand</code> event.</p>
<p><code v-pre>OnGetBackUpdatedValues</code>
write this event to return updated values from server. You can call <code v-pre>TCustomSQLDataDriverEh.DefaultGetUpdatedServerValues</code> method to process action by default. <code v-pre>TCustomSQLDataDriverEh.DefaultGetUpdatedServerValues</code> call <code v-pre>DefaultSQLDataDriverResolver.GetBackUpdatedValues</code>. If it was not processed in <code v-pre>DefaultSQLDataDriverResolver</code> then it call <code v-pre>InternalGetServerSpecOperations.GetBackUpdatedValues</code>. <code v-pre>InternalGetServerSpecOperations</code> returns object of <code v-pre>TServerSpecOperationsEh</code> type.</p>
<p><code v-pre>Property TXXXDataDriverEh.SpecParams</code>
Property SpecParams kept a list of parameters and values. <code v-pre>TXXXDataDriverEh</code> use them when performing SQL expressions. Value of each parameter have to be wrote in the separate line in the format <code v-pre>PARAMETER_NAME =VALUE</code>. Depending on the type of the server (<code v-pre>InterBase</code>, <code v-pre>Oracle</code>, <code v-pre>MSSQL</code>, <code v-pre>Informix</code>) <code v-pre>SpecParams</code> can contain the following parameters.</p>
<h5 id="on-interaction-with-interbase-server" tabindex="-1"><a class="header-anchor" href="#on-interaction-with-interbase-server" aria-hidden="true">#</a> On interaction with InterBase server:</h5>
 <dd>
<p><code v-pre>GENERATOR</code> - defines a name of the InterBase generator. DataDriver uses this parameter to get current value of generator after the insertion of new record.</p>
<p><code v-pre>GENERATOR_FIELD</code> - defines a name of the field, which will be assigned current value of the generator after the insertion of new record.</p>
<p><code v-pre>AUTO_INCREMENT_FIELD</code> - defines a name of the field, which DataDriver will set AutoIncremet type. It is used on making a structure of the internal array of record.</p>
 </dd>
<h5 id="on-interaction-with-oracle-server" tabindex="-1"><a class="header-anchor" href="#on-interaction-with-oracle-server" aria-hidden="true">#</a> On interaction with Oracle server:</h5>
<dd>
<p><code v-pre>SEQUENCE</code> - will assign a name of the field Oracle sequences. DataDriver uses this parameter for the reception of the current value of the sequence after the insertion of new record.</p>
<p><code v-pre>SEQUENCE_FIELD</code> - will assign a name of the field, which will be assigned current value of the sequence after the insertion of new record.</p>
<p><code v-pre>AUTO_INCREMENT_FIELD</code> - defines a name of the field, which DataDriver will set AutoIncremet type. It is used on making a structure of the internal array of record.</p>
 </dd>
<h5 id="on-interaction-with-mssql-server" tabindex="-1"><a class="header-anchor" href="#on-interaction-with-mssql-server" aria-hidden="true">#</a> On interaction with MSSQL server:</h5>
<dd>
<p><code v-pre>AUTO_INCREMENT_FIELD</code> - defines a name of the field, which DataDriver will set AutoIncremet type. It is used on making a structure of the internal array of record.</p>
</dd>
<h5 id="on-interaction-with-informix-server" tabindex="-1"><a class="header-anchor" href="#on-interaction-with-informix-server" aria-hidden="true">#</a> On interaction with Informix server:</h5>
<dd>
<p><code v-pre>AUTO_INCREMENT_FIELD</code> - defines a name of the field, which DataDriver will set AutoIncremet type. It is used on making a structure of the internal array of record.</p>
</dd>
<h4 id="example-of-the-list-of-parameters-for-interbase-server" tabindex="-1"><a class="header-anchor" href="#example-of-the-list-of-parameters-for-interbase-server" aria-hidden="true">#</a> Example of the list of parameters for InterBase server:</h4>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="language-text"><code>   GENERATOR=EMP_NO_GEN
   GENERATOR_FIELD=emp_no
   AUTO_INCREMENT_FIELD=emp_no
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>SQL expression for the insertion of record must contain EMP_NO_GEN generator.</p>
<div class="language-sql line-numbers-mode" data-ext="sql"><pre v-pre class="language-sql"><code>   <span class="token keyword">insert</span> <span class="token keyword">into</span>
     employee <span class="token punctuation">(</span>EMP_NO<span class="token punctuation">,</span> FIRST_NAME<span class="token punctuation">)</span>
   <span class="token keyword">values</span>
     <span class="token punctuation">(</span>:EMP_NO_GEN<span class="token punctuation">,</span> :FIRST_NAME<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


